### ISSUE TITLE
Hp bios disable code 60640577

### ISSUE THREAD

**Issue by Somarriba1982** [bacher09/pwgen-for-bios#50] opened 2018-09-29 02:40 UTC
I am not able to unlock my HP using the code generated.

Disable code 60640577

Thanks

**Comment by Somarriba1982** [comment] 2018-10-13 00:37
Plz help guys. I cannot access to my laptop yet.

**Comment by qasimtoep01** [comment] 2018-12-26 20:41
password is: 75728579

**Comment by qasimtoep01** [comment] 2019-01-05 17:59
are you sure your Disable code is  60640577 and not i60640577 ????

**Comment by Somarriba1982** [comment] 2019-01-05 18:08
It had the "i" at the beginning but the online calculators shown invalid every time at included it.

Unexpectedly the pc is giving me a totally different system disable code right now. Here it is
i 84987200

**Comment by Somarriba1982** [comment] 2019-01-05 18:10
I can send you a screenshot right now if you like

**Comment by qasimtoep01** [comment] 2019-01-05 18:19
go to ebay, online calculator can´t do it for you

**Comment by Somarriba1982** [comment] 2019-01-05 18:32
Can you unlock it for me? I can make the payment through paypal or any other money transfer. I do not trust at ebay dudes. Even I know that you could be one. :(

**Comment by qasimtoep01** [comment] 2019-01-05 18:41
https://www.ebay.com/itm/HP-bios-power-on-password-8-digit-code-starting-with-i-like-i-12345678/143073551278?hash=item214fd923ae:g:JaoAAOSwAx9cKcVj:rk:11:pf:0

**Comment by moslimbios** [comment] 2019-01-05 20:02
https://www.ebay.com/itm/323574422646

Le sam. 5 janv. 2019 à 19:41, qasimtoep01 <notifications@github.com> a
écrit :

**Comment by EvanCarroll** [comment] 2019-01-24 03:20
This issue is a dupe of https://github.com/bacher09/pwgen-for-bios/issues/52

**Comment by bacher09** [comment] 2020-06-15 10:42
Closing as duplicate, also this should be already supported.

**Closed by bacher09** 2020-06-15 10:42 UTC
