### ISSUE TITLE
Hp. Pavillion (i 75917830) 

### ISSUE THREAD

**Issue by LazyAAD** [bacher09/pwgen-for-bios#38] opened 2018-03-18 14:09 UTC
I was able to find the code but that code didn't work because u can only type 12 letter/ number. Please help i have written my code up in the title

**Comment by bobpaw** [comment] 2018-04-08 14:52
Does the code change with each reboot? If it does it's apparently called a "hex halt". It's more secure and used on newer models. It doesn't have a master solution yet.

**Comment by EvanCarroll** [comment] 2019-01-24 03:21
This issue is a duplicate of https://github.com/bacher09/pwgen-for-bios/issues/52

**Comment by bacher09** [comment] 2020-06-15 10:40
This already supported in 1580bf4ac103e54b3bd5741556f7f795e0ddecd1 and available on [beta site version](https://beta.bios-pw.org).

**Closed by bacher09** 2020-06-15 10:40 UTC
